language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - sys-img-armeabi-v7a-android-21
    - extra-google-m2repository
    - extra-android-m2repository
env:
  global:
    - ADB_INSTALL_TIMEOUT=4

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew connectedAndroidTest

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  slack:
    secure: GZkX6pTK/W5NiS14/jHYLaUjVKSYy79wdZOWkauH42LjUMdZtW1r/eRbh6GMbmxiaFGMTyXaoNfhY0dTdZSM56oJtMEy3TjtpYKtOeoDg1Cbu6pQu43yfxPGRcDFFVSWHhtPhnP55SOxCwT9KnuCYqRifpOF8R7K1yxrO9zisrLZv4zpgu4Y1YS6cT36Hi45/eOuXRFolojdaJrWo6q36E+Gm5tOTrFyqEuBVorhIZW4EI4USsrO/dgmyNR2c1uYioOJUe8iIHhgO3KQRitDcoGGdjxvk/cpl6xf0aPnNNx/b+OFGqv63SpNxOGNc2oyq6WyktRPK/E9v/057RwwCtI3ELXoo4KFRSUC+a886v0lTi8LQsVd0aOKtGhZpLLoasAlI0uguZgb6HtR3cWy9e/mI3tBA35oUUM4kmgp7m3G0FoNfd0so7ZUDDaL1WGBizpuclcqlew+4vlUNc+BZyUNjpQE+CJRYrl4ZsMx3AtRWzLkTO6VZndPswTBqbIMHonBFXEdcA8H7o75gVsA9CL02sagXLb3bnAoR8RK/ssojoIScNzDSBi36W3V9v5/2wrHoDZPvNLTQbYrOnqkvnNVociW52LE5IP14rX48gUuPfYMilbH+APw5LaWIwo2lllKUNoVSy3HqxPMDlaEFke0CMASMMqjr0Y0dlGhHMw=
